"""Add Anime tables

Revision ID: 52579467e8bc
Revises: d96a3386d52e
Create Date: 2026-01-25 19:38:49.279152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52579467e8bc'
down_revision: Union[str, Sequence[str], None] = 'd96a3386d52e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('alt_titles', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anime_title'), 'anime', ['title'], unique=False)
    op.add_column('uploaded_files', sa.Column('anime_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'uploaded_files', 'anime', ['anime_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploaded_files', type_='foreignkey')
    op.drop_column('uploaded_files', 'anime_id')
    op.drop_index(op.f('ix_anime_title'), table_name='anime')
    op.drop_table('anime')
    # ### end Alembic commands ###
