"""Initial tables

Revision ID: d96a3386d52e
Revises: 
Create Date: 2025-11-23 21:03:23.444854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd96a3386d52e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anime_title', sa.String(), nullable=False),
    sa.Column('episode', sa.Integer(), nullable=False),
    sa.Column('uploaded_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('uploader_user_id', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_message_id', sa.BigInteger(), nullable=False),
    sa.Column('vault_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('vault_message_id', sa.BigInteger(), nullable=False),
    sa.Column('ep_lang', sa.String(), nullable=False),
    sa.Column('ep_qual', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('filesize', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_files_anime_title'), 'uploaded_files', ['anime_title'], unique=False)
    op.create_index(op.f('ix_uploaded_files_episode'), 'uploaded_files', ['episode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_files_episode'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_anime_title'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    # ### end Alembic commands ###
